#!/bin/bash 

manifest=$1
srv=https://api.tizen.org
project=${2:-Tizen:Common}

function get_pkg_infos() {
	local srv=$1
	local project=$2
	local pkgname=$3

	local tmpfile=$(mktemp)
	trap "rm -f $tmpfile" STOP INT QUIT EXIT
	
	osc -A $srv list -e $project $pkgname >$tmpfile 2>/dev/null
	[[ $? -ne 0 ]] && return 1

	# find spec file name
	osc -A $srv cat $project $pkgname $(egrep "\.spec$" $tmpfile) >$tmpfile 2>/dev/null
	repo=$(grep VCS: $tmpfile | awk '{print $2;}' | cut -f1 -d'#')
	rev=$(grep VCS: $tmpfile | awk '{print $2;}' | cut -f2 -d'#')
	license=$(grep License: $tmpfile | sed 's/License:[ \t]*//g' | awk '{printf("%s/",$0);}' | sed 's|/$||g')
	echo "$pkgname;$repo;$rev;$license"

	return 0
}

for path in $(xml sel -t -v "/manifest/project/@name" $manifest); do 
	get_pkg_infos $srv $project $(basename $path)
done
